const sampleData = {
  products: [
    {
      name: 'T-shirt Sara Sporting Stretch',
      slug: 'sara-sporting-stretch-shirt',
      category: 'Man shirt',
      description: 'Classic Sara "Comfi" ',
      images: ['/images/sample-products/p1-1.jpg', '/images/sample-products/p1-2.jpg'],
      price: 59.99,
      brand: 'Sara',
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeature: true,
      banner: 'banner-1.jpg',
    },
    {
      name: 'Long-Sleeved Shirt Luke Pro',
      slug: 'luke-pro-long-sleeved-shirt',
      category: 'Man shirt',
      description: 'Style and prime comfort',
      images: ['/images/sample-products/p2-1.jpg', '/images/sample-products/p2-2.jpg'],
      price: 85.9,
      brand: 'Luke Pro',
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeature: true,
      banner: 'banner-2.jpg',
    },
    {
      name: 'Classic T-shirt Tommy Hilfiger',
      slug: 'tommy-hilfiger-classic-fit-dress-shirt',
      category: 'Man shirt',
      description: 'Balance t-shirt',
      images: ['/images/sample-products/p3-1.jpg', '/images/sample-products/p3-2.jpg'],
      price: 99.95,
      brand: 'Tommy Hilfiger',
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeature: false,
      banner: null,
    },
    {
      name: 'Slim shirt Calvin Klein',
      slug: 'calvin-klein-slim-fit-stretch-shirt',
      category: 'Man shirt',
      description: 'New Style',
      images: ['/images/sample-products/p4-1.jpg', '/images/sample-products/p4-2.jpg'],
      price: 39.95,
      brand: 'Calvin Klein',
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeature: false,
      banner: null,
    },
    {
      name: 'Oxford shirt Sara Ralph Lauren',
      slug: 'sara-ralph-lauren-oxford-shirt',
      category: 'Man shirt',
      description: 'Lauren style Sara',
      images: ['/images/sample-products/p5-1.jpg', '/images/sample-products/p5-2.jpg'],
      price: 79.99,
      brand: 'Sara',
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeature: false,
      banner: null,
    },
    {
      name: 'Pink Hoodie Sara Classic',
      slug: 'sara-classic-pink-hoodie',
      category: 'Man hoodie',
      description: 'Style new day',
      images: ['/images/sample-products/p6-1.jpg', '/images/sample-products/p6-2.jpg'],
      price: 99.99,
      brand: 'Sara',
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeature: true,
      banner: null,
    },
  ],
};

export default sampleData;
